# Generated by Django 4.2.28 on 2026-02-27 18:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ceo', 'PDG'), ('lab_manager', 'Responsable Laboratoire'), ('production_manager', 'Responsable Production'), ('warehouse_manager', 'Responsable Entrepôt'), ('viewer', 'Visiteur')], default='viewer', max_length=25)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_role', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rôle Dashboard',
                'verbose_name_plural': 'Rôles Dashboard',
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('low_stock', 'Stock faible'), ('expiry', 'Expiration proche'), ('qc_fail', 'Échec CQ'), ('regulatory_deadline', 'Échéance réglementaire'), ('info', 'Information')], max_length=30)),
                ('severity', models.CharField(choices=[('critical', 'Critique'), ('warning', 'Avertissement'), ('info', 'Information')], default='warning', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alerte',
                'verbose_name_plural': 'Alertes',
                'ordering': ['-created_at'],
            },
        ),
    ]
