# Generated by Django 4.2.28 on 2026-02-27 18:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stock', '0001_initial'),
        ('rnd', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=50, unique=True, verbose_name='Numéro de lot')),
                ('planned_quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantité planifiée (kg)')),
                ('actual_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Quantité réelle (kg)')),
                ('production_date', models.DateField(default=django.utils.timezone.now, verbose_name='Date de production')),
                ('status', models.CharField(choices=[('planned', 'Planifié'), ('in_progress', 'En cours'), ('completed', 'Terminé'), ('cancelled', 'Annulé'), ('on_hold', 'En attente')], default='planned', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('finished_lot', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_batch', to='stock.lot')),
                ('formulation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_batches', to='rnd.formulation')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operated_batches', to=settings.AUTH_USER_MODEL)),
                ('responsible', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lot de production',
                'verbose_name_plural': 'Lots de production',
                'ordering': ['-production_date'],
            },
        ),
        migrations.CreateModel(
            name='QCCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=200, verbose_name='Nom du test')),
                ('specification', models.CharField(blank=True, max_length=200, verbose_name='Spécification')),
                ('measured_value', models.CharField(blank=True, max_length=100, verbose_name='Valeur mesurée')),
                ('result', models.CharField(choices=[('pass', 'Conforme'), ('fail', 'Non conforme'), ('pending', 'En attente')], default='pending', max_length=10)),
                ('performed_at', models.DateTimeField(blank=True, null=True, verbose_name='Date/heure')),
                ('notes', models.TextField(blank=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qc_checks', to='production.productionbatch')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_qc', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contrôle qualité',
                'verbose_name_plural': 'Contrôles qualité',
            },
        ),
        migrations.CreateModel(
            name='ProductionRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('lab_manager', 'Responsable Laboratoire'), ('operator', 'Opérateur'), ('qc_technician', 'Technicien CQ'), ('viewer', 'Visiteur')], default='viewer', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='production_role', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rôle Production',
                'verbose_name_plural': 'Rôles Production',
            },
        ),
        migrations.CreateModel(
            name='BatchRawMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_name', models.CharField(blank=True, max_length=200, verbose_name='Ingrédient')),
                ('ingredient_percentage', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='% formulation')),
                ('required_quantity', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Quantité requise')),
                ('actual_quantity', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Quantité réelle utilisée')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_materials', to='production.productionbatch')),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='stock.lot')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='stock.material')),
            ],
            options={
                'verbose_name': 'Matière première du lot',
                'verbose_name_plural': 'Matières premières du lot',
            },
        ),
    ]
