# Generated by Django 4.2.29 on 2026-03-26 20:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("production", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Equipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Nom de la machine"),
                ),
                (
                    "serial_number",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Numéro de série"
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "purchase_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date d'achat"
                    ),
                ),
                (
                    "last_maintenance",
                    models.DateField(
                        blank=True, null=True, verbose_name="Dernière maintenance"
                    ),
                ),
                (
                    "next_maintenance",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Prochaine maintenance prévue",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="En service"),
                ),
            ],
            options={
                "verbose_name": "Équipement (GMAO)",
                "verbose_name_plural": "Équipements (GMAO)",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="MaintenanceLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        default=django.utils.timezone.now,
                        verbose_name="Date d'intervention",
                    ),
                ),
                (
                    "description",
                    models.TextField(verbose_name="Détails de la maintenance"),
                ),
                (
                    "performed_by",
                    models.CharField(
                        max_length=150,
                        verbose_name="Effectué par (Technicien ou externe)",
                    ),
                ),
                (
                    "cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Coût estimé",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "equipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="production.equipment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Intervention de maintenance",
                "verbose_name_plural": "Interventions de maintenance",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="BatchTimeLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        default=django.utils.timezone.now,
                        verbose_name="Date de travail",
                    ),
                ),
                (
                    "duration_hours",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        verbose_name="Heures travaillées",
                    ),
                ),
                (
                    "hourly_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=8,
                        verbose_name="Coût horaire",
                    ),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_logs",
                        to="production.productionbatch",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Employé / Opérateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Suivi Main d'Œuvre",
                "verbose_name_plural": "Suivis Main d'Œuvre",
                "ordering": ["-date"],
            },
        ),
    ]
