# Generated by Django 4.2.29 on 2026-03-26 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesorder",
            name="discount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=5,
                verbose_name="Remise globale (%)",
            ),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="invoice_number",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="N° Facture"
            ),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("unpaid", "Non payé"),
                    ("partial", "Partiellement payé"),
                    ("paid", "Payé"),
                ],
                default="unpaid",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="tva_rate",
            field=models.DecimalField(
                decimal_places=2, default=19.0, max_digits=5, verbose_name="TVA (%)"
            ),
        ),
    ]
