# Generated by Django 4.2.28 on 2026-02-27 18:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rnd', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_number', models.CharField(max_length=100, verbose_name='Numéro de lot')),
                ('supplier', models.CharField(blank=True, max_length=200, verbose_name='Fournisseur')),
                ('initial_quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantité initiale')),
                ('current_quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantité actuelle')),
                ('reception_date', models.DateField(default=django.utils.timezone.now, verbose_name='Date réception')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Date expiration')),
                ('unit_cost', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Coût unitaire')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='Emplacement')),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lot',
                'verbose_name_plural': 'Lots',
                'ordering': ['-reception_date'],
            },
        ),
        migrations.CreateModel(
            name='MaterialCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Catégorie')),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Catégorie matière',
                'verbose_name_plural': 'Catégories matières',
            },
        ),
        migrations.CreateModel(
            name='StockRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('warehouse_manager', 'Responsable Entrepôt'), ('purchase_officer', 'Responsable Achats'), ('production_manager', 'Responsable Production'), ('viewer', 'Visiteur')], default='viewer', max_length=25)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock_role', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rôle Stock',
                'verbose_name_plural': 'Rôles Stock',
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('reception', 'Réception'), ('production_use', 'Utilisation production'), ('production_output', 'Sortie production'), ('sale', 'Vente'), ('adjustment', 'Ajustement'), ('return', 'Retour'), ('loss', 'Perte')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantité (+ entrée / - sortie)')),
                ('reference', models.CharField(blank=True, max_length=200, verbose_name='Référence')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='stock.lot')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mouvement de stock',
                'verbose_name_plural': 'Mouvements de stock',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Code')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('material_type', models.CharField(choices=[('raw_material', 'Matière première'), ('packaging', 'Emballage'), ('finished_product', 'Produit fini')], max_length=20)),
                ('unit', models.CharField(choices=[('kg', 'Kilogramme'), ('g', 'Gramme'), ('L', 'Litre'), ('mL', 'Millilitre'), ('pcs', 'Pièce'), ('box', 'Boîte')], default='kg', max_length=10)),
                ('minimum_stock', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Stock minimum')),
                ('reorder_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Quantité de commande')),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('ingredient_ref', models.CharField(blank=True, max_length=200, verbose_name='Réf. ingrédient')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock.materialcategory')),
                ('ingredient', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_material', to='rnd.ingredient', verbose_name='Ingrédient R&D lié')),
            ],
            options={
                'verbose_name': 'Matière / Produit',
                'verbose_name_plural': 'Matières / Produits',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='lot',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='stock.material'),
        ),
    ]
