# Generated by Django 4.2.28 on 2026-03-18 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='holding_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Coût de stockage/unité/mois (DT)'),
        ),
        migrations.AddField(
            model_name='material',
            name='order_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Coût par commande (DT)'),
        ),
        migrations.AlterField(
            model_name='material',
            name='material_type',
            field=models.CharField(choices=[('raw_material', 'Matière première'), ('packaging', 'Emballage'), ('finished_product', 'Produit fini'), ('laboratory', 'Matériel laboratoire')], max_length=20),
        ),
    ]
