# Generated by Django 4.2.29 on 2026-03-26 20:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("stock", "0002_material_holding_cost_material_order_cost_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lot",
            name="qc_status",
            field=models.CharField(
                choices=[
                    ("quarantine", "En Quarantaine"),
                    ("approved", "Approuvé (Conforme)"),
                    ("rejected", "Rejeté (Non Conforme)"),
                ],
                default="quarantine",
                max_length=20,
                verbose_name="Statut Qualité",
            ),
        ),
        migrations.AlterField(
            model_name="lot",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="lot",
            name="current_quantity",
            field=models.DecimalField(
                decimal_places=3, max_digits=12, verbose_name="Quantité actuelle"
            ),
        ),
        migrations.AlterField(
            model_name="lot",
            name="expiry_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Date d'expiration"
            ),
        ),
        migrations.AlterField(
            model_name="lot",
            name="initial_quantity",
            field=models.DecimalField(
                decimal_places=3, max_digits=12, verbose_name="Quantité initiale"
            ),
        ),
        migrations.AlterField(
            model_name="lot",
            name="location",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Emplacement géographique"
            ),
        ),
        migrations.AlterField(
            model_name="lot",
            name="lot_number",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="Numéro de lot"
            ),
        ),
        migrations.AlterField(
            model_name="lot",
            name="reception_date",
            field=models.DateField(
                default=django.utils.timezone.now,
                verbose_name="Date de réception / production",
            ),
        ),
        migrations.AlterField(
            model_name="lot",
            name="supplier",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Fournisseur (Supplier)"
            ),
        ),
        migrations.AlterField(
            model_name="lot",
            name="unit_cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                max_digits=10,
                null=True,
                verbose_name="Coût unitaire",
            ),
        ),
    ]
