# Generated by Django 4.2.28 on 2026-02-27 18:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rnd', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SafetyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_number', models.CharField(max_length=50, unique=True, verbose_name='Numéro RSP')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('under_review', 'En révision'), ('approved', 'Approuvé'), ('expired', 'Expiré')], default='draft', max_length=20)),
                ('safety_assessor', models.CharField(max_length=200, verbose_name='Évaluateur sécurité')),
                ('issue_date', models.DateField(blank=True, null=True, verbose_name="Date d'émission")),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Date expiration')),
                ('conclusion', models.TextField(blank=True, verbose_name='Conclusion')),
                ('document', models.FileField(blank=True, null=True, upload_to='safety_reports/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('formulation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='rnd.formulation')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='safety_reports', to='rnd.product')),
            ],
            options={
                'verbose_name': 'Rapport de sécurité',
                'verbose_name_plural': 'Rapports de sécurité',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RegulatoryRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('regulatory_officer', 'Responsable Réglementaire'), ('qa_manager', 'Responsable QA'), ('viewer', 'Visiteur')], default='viewer', max_length=25)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='regulatory_role', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rôle Réglementaire',
                'verbose_name_plural': 'Rôles Réglementaires',
            },
        ),
        migrations.CreateModel(
            name='ProductCompliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('in_review', 'En cours de révision'), ('compliant', 'Conforme'), ('non_compliant', 'Non conforme'), ('exempted', 'Exempté')], default='pending', max_length=20)),
                ('eu_regulation', models.BooleanField(default=False, verbose_name='Rég. UE 1223/2009')),
                ('responsible_person', models.CharField(blank=True, max_length=200, verbose_name='Personne responsable')),
                ('responsible_person_address', models.TextField(blank=True, verbose_name='Adresse RP')),
                ('last_review_date', models.DateField(blank=True, null=True, verbose_name='Dernière révision')),
                ('next_review_date', models.DateField(blank=True, null=True, verbose_name='Prochaine révision')),
                ('notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='compliance', to='rnd.product')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conformité produit',
                'verbose_name_plural': 'Conformités produits',
            },
        ),
        migrations.CreateModel(
            name='CPNPNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_number', models.CharField(max_length=100, unique=True, verbose_name='Numéro CPNP')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('submitted', 'Soumis'), ('accepted', 'Accepté'), ('rejected', 'Rejeté'), ('withdrawn', 'Retiré')], default='pending', max_length=20)),
                ('submission_date', models.DateField(blank=True, null=True, verbose_name='Date soumission')),
                ('acceptance_date', models.DateField(blank=True, null=True, verbose_name='Date acceptation')),
                ('market', models.CharField(default='UE', max_length=100, verbose_name='Marché')),
                ('product_category', models.CharField(blank=True, max_length=200)),
                ('frame_formulation', models.BooleanField(default=False, verbose_name='Formulation cadre')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cpnp_notifications', to='rnd.product')),
            ],
            options={
                'verbose_name': 'Notification CPNP',
                'verbose_name_plural': 'Notifications CPNP',
            },
        ),
        migrations.CreateModel(
            name='BPFDeclaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('declaration_number', models.CharField(max_length=50, unique=True, verbose_name='Numéro BPF')),
                ('status', models.CharField(choices=[('not_started', 'Non commencé'), ('in_progress', 'En cours'), ('completed', 'Complété'), ('submitted', 'Soumis')], default='not_started', max_length=20)),
                ('facility_name', models.CharField(max_length=200, verbose_name="Nom de l'établissement")),
                ('facility_address', models.TextField(verbose_name='Adresse')),
                ('manufacturing_site', models.CharField(blank=True, max_length=200)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bpf_declarations', to='rnd.product')),
            ],
            options={
                'verbose_name': 'Déclaration BPF',
                'verbose_name_plural': 'Déclarations BPF',
            },
        ),
        migrations.CreateModel(
            name='ProductLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=20, verbose_name='Version')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('approved', 'Approuvé'), ('obsolete', 'Obsolète')], default='draft', max_length=20)),
                ('language', models.CharField(default='Français', max_length=50, verbose_name='Langue')),
                ('ingredient_list', models.TextField(verbose_name='Liste INCI')),
                ('claims', models.TextField(blank=True, verbose_name='Claims marketing')),
                ('warnings', models.TextField(blank=True, verbose_name='Avertissements')),
                ('net_quantity', models.CharField(blank=True, max_length=50, verbose_name='Contenu net')),
                ('label_file', models.FileField(blank=True, null=True, upload_to='labels/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_labels', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_labels', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='rnd.product')),
            ],
            options={
                'verbose_name': 'Étiquette',
                'verbose_name_plural': 'Étiquettes',
                'unique_together': {('product', 'version', 'language')},
            },
        ),
    ]
