# Generated by Django 4.2.29 on 2026-03-26 20:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("rnd", "0002_formulation_labor_cost_formulation_packaging_cost_and_more"),
        ("regulatory", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegulatoryDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        help_text="Ex: Tunisie, UE, Maroc, UAE...",
                        max_length=100,
                        verbose_name="Pays / Marché",
                    ),
                ),
                (
                    "authority",
                    models.CharField(
                        blank=True,
                        help_text="Ex: INNORPI, Ministère de la Santé, SFDA...",
                        max_length=200,
                        verbose_name="Autorité",
                    ),
                ),
                (
                    "doc_type",
                    models.CharField(
                        choices=[
                            ("registration", "Enregistrement"),
                            ("certificate", "Certificat"),
                            ("license", "Licence / Autorisation"),
                            ("analysis", "Certificat d'analyse"),
                            ("safety", "Rapport de sécurité"),
                            ("technical", "Fiche technique"),
                            ("label", "Étiquette approuvée"),
                            ("other", "Autre"),
                        ],
                        default="certificate",
                        max_length=20,
                        verbose_name="Type de document",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Numéro / Référence"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("valid", "Valide"),
                            ("pending", "En attente"),
                            ("expired", "Expiré"),
                            ("rejected", "Rejeté"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "issue_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date d'émission"
                    ),
                ),
                (
                    "expiry_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date d'expiration"
                    ),
                ),
                (
                    "document_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="regulatory_docs/",
                        verbose_name="Fichier (PDF, image...)",
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="regulatory_documents",
                        to="rnd.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document réglementaire",
                "verbose_name_plural": "Documents réglementaires",
                "ordering": ["-created_at"],
            },
        ),
    ]
