# Generated by Django 4.2.28 on 2026-02-27 18:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Formulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=20, verbose_name='Version')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('under_review', 'En révision'), ('approved', 'Approuvée'), ('obsolete', 'Obsolète')], default='draft', max_length=20)),
                ('batch_size', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Taille du lot (kg)')),
                ('ph_min', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='pH min')),
                ('ph_max', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='pH max')),
                ('viscosity', models.CharField(blank=True, max_length=100, verbose_name='Viscosité')),
                ('appearance', models.CharField(blank=True, max_length=200, verbose_name='Aspect')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_formulations', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_formulations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Formulation',
                'verbose_name_plural': 'Formulations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('inci_name', models.CharField(blank=True, max_length=200, verbose_name='Nom INCI')),
                ('cas_number', models.CharField(blank=True, max_length=50, verbose_name='Numéro CAS')),
                ('category', models.CharField(choices=[('active', 'Actif'), ('emulsifier', 'Émulsifiant'), ('preservative', 'Conservateur'), ('fragrance', 'Parfum'), ('colorant', 'Colorant'), ('solvent', 'Solvant'), ('other', 'Autre')], default='other', max_length=20)),
                ('supplier', models.CharField(blank=True, max_length=200, verbose_name='Fournisseur')),
                ('max_concentration', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='Concentration max (%)')),
                ('is_restricted', models.BooleanField(default=False, verbose_name='Restreint')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ingrédient',
                'verbose_name_plural': 'Ingrédients',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StabilityTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(choices=[('room_temp', 'Température ambiante (25°C)'), ('accelerated', 'Accéléré (40°C/75%RH)'), ('freeze_thaw', 'Congélation-décongélation'), ('uv', 'Exposition UV'), ('cold', 'Froid (4°C)')], max_length=20)),
                ('duration_weeks', models.PositiveIntegerField(verbose_name='Durée (semaines)')),
                ('start_date', models.DateField(verbose_name='Date début')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Date fin')),
                ('result', models.CharField(choices=[('pass', 'Conforme'), ('fail', 'Non conforme'), ('pending', 'En cours')], default='pending', max_length=10)),
                ('ph_initial', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('ph_final', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('appearance_ok', models.BooleanField(blank=True, null=True, verbose_name='Aspect OK')),
                ('odor_ok', models.BooleanField(blank=True, null=True, verbose_name='Odeur OK')),
                ('observations', models.TextField(blank=True, verbose_name='Observations')),
                ('formulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stability_tests', to='rnd.formulation')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Test de stabilité',
                'verbose_name_plural': 'Tests de stabilité',
            },
        ),
        migrations.CreateModel(
            name='RndRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('scientist', 'Scientist'), ('lab_manager', 'Lab Manager'), ('regulatory', 'Regulatory'), ('viewer', 'Viewer')], default='viewer', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rnd_role', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rôle R&D',
                'verbose_name_plural': 'Rôles R&D',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('reference', models.CharField(max_length=50, unique=True, verbose_name='Référence')),
                ('category', models.CharField(choices=[('skincare', 'Soin peau'), ('haircare', 'Soin cheveux'), ('makeup', 'Maquillage'), ('fragrance', 'Parfum'), ('bodycare', 'Soin corps'), ('suncare', 'Solaire'), ('other', 'Autre')], default='skincare', max_length=20)),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('status', models.CharField(choices=[('development', 'En développement'), ('testing', 'En test'), ('approved', 'Approuvé'), ('discontinued', 'Arrêté')], default='development', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FormulationIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(choices=[('A', 'Phase A'), ('B', 'Phase B'), ('C', 'Phase C'), ('D', 'Phase D'), ('other', 'Autre')], default='A', max_length=10)),
                ('percentage', models.DecimalField(decimal_places=4, max_digits=8, verbose_name='Pourcentage (%)')),
                ('function', models.CharField(blank=True, max_length=200, verbose_name='Fonction')),
                ('order', models.PositiveIntegerField(default=0)),
                ('formulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formulation_ingredients', to='rnd.formulation')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rnd.ingredient')),
            ],
            options={
                'verbose_name': 'Ingrédient de formulation',
                'verbose_name_plural': 'Ingrédients de formulation',
                'ordering': ['phase', 'order'],
            },
        ),
        migrations.AddField(
            model_name='formulation',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formulations', to='rnd.product'),
        ),
        migrations.AlterUniqueTogether(
            name='formulation',
            unique_together={('product', 'version')},
        ),
    ]
