# Generated by Django 4.2.29 on 2026-03-26 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("rnd", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="formulation",
            name="labor_cost",
            field=models.DecimalField(
                decimal_places=3,
                default=0,
                max_digits=10,
                verbose_name="Coût de la main d'œuvre unitaire (DT)",
            ),
        ),
        migrations.AddField(
            model_name="formulation",
            name="packaging_cost",
            field=models.DecimalField(
                decimal_places=3,
                default=0,
                max_digits=10,
                verbose_name="Coût d'emballage unitaire (DT)",
            ),
        ),
        migrations.AddField(
            model_name="formulation",
            name="target_margin",
            field=models.DecimalField(
                decimal_places=2,
                default=50,
                max_digits=5,
                verbose_name="Marge ciblée (%)",
            ),
        ),
        migrations.AddField(
            model_name="ingredient",
            name="addition_phase",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Phase d'ajout"
            ),
        ),
        migrations.AddField(
            model_name="ingredient",
            name="applications",
            field=models.TextField(blank=True, verbose_name="Applications cosmétiques"),
        ),
        migrations.AddField(
            model_name="ingredient",
            name="aspect",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Aspect physique"
            ),
        ),
        migrations.AddField(
            model_name="ingredient",
            name="certification",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Certifications"
            ),
        ),
        migrations.AddField(
            model_name="ingredient",
            name="description",
            field=models.TextField(blank=True, verbose_name="Description"),
        ),
        migrations.AddField(
            model_name="ingredient",
            name="dosage_max",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=8,
                null=True,
                verbose_name="Dosage max (%)",
            ),
        ),
        migrations.AddField(
            model_name="ingredient",
            name="dosage_min",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=8,
                null=True,
                verbose_name="Dosage min (%)",
            ),
        ),
        migrations.AddField(
            model_name="ingredient",
            name="origin",
            field=models.CharField(blank=True, max_length=200, verbose_name="Origine"),
        ),
        migrations.AddField(
            model_name="ingredient",
            name="solubility",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Solubilité"
            ),
        ),
        migrations.AddField(
            model_name="ingredient",
            name="storage",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Conditions de stockage"
            ),
        ),
        migrations.AddField(
            model_name="ingredient",
            name="usage_mode",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Mode d'ajout"
            ),
        ),
        migrations.CreateModel(
            name="IngredientCompatibility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("compatible", "Compatible"),
                            ("incompatible", "Incompatible"),
                            ("caution", "Précaution"),
                        ],
                        default="compatible",
                        max_length=15,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "ingredient_a",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compatibilities",
                        to="rnd.ingredient",
                    ),
                ),
                (
                    "ingredient_b",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compatible_with",
                        to="rnd.ingredient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Compatibilité",
                "verbose_name_plural": "Compatibilités",
                "unique_together": {("ingredient_a", "ingredient_b")},
            },
        ),
    ]
