# Generated by Django 4.2.28 on 2026-03-18 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='currency',
            field=models.CharField(choices=[('TND', 'Dinar Tunisien'), ('EUR', 'Euro'), ('USD', 'Dollar US'), ('GBP', 'Livre Sterling')], default='TND', max_length=3, verbose_name='Devise'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=10, verbose_name='Taux de change vers TND'),
        ),
    ]
